# enter stuff you want to backup here.
# one file or directory per line
# prefix entries with "-" to exclude them from broader directory backups
# wildcard entries are allowed for file patterns
#
# /var/etc/rcS.local			# an example for a single file
# /etc/neutrino/config/tuxtxt/		# an example for a complete directory

/etc/neutrino/config/tobackup.conf
/etc/neutrino/config/settingsupdate.conf
/etc/neutrino/config/neutrino.conf
/etc/neutrino/config/nhttpd.conf
/etc/neutrino/config/encoding.conf
/etc/neutrino/config/epglanguages.conf
/etc/neutrino/config/scan.conf
/etc/neutrino/config/timerd.conf
/etc/neutrino/config/weather-favorites.xml
/etc/neutrino/config/cables.xml
/etc/neutrino/config/providermap.xml
/etc/neutrino/config/radio-favorites.xml
/etc/neutrino/config/radio-stations.xml
/etc/neutrino/config/satellites.xml
/etc/neutrino/config/terrestrial.xml
/etc/neutrino/config/EPGscan.conf
/etc/neutrino/config/shellexec.conf
/etc/neutrino/config/stb-startup.conf
/etc/neutrino/config/auto-record-cleaner.*
/etc/neutrino/config/pr-auto-timer.*
/etc/neutrino/config/tuxcal/
/etc/neutrino/config/tuxmail/
/etc/neutrino/config/tuxtxt/tuxtxt2.conf
/etc/neutrino/config/tuxwetter/tuxwetter.conf
/etc/neutrino/config/tuxwetter/tuxwetter.mcfg
/etc/neutrino/config/zapit/
/etc/neutrino/plugins/webradio/webradio_usr.xml
/etc/neutrino/webtv/webtv_usr.xml
/var/tuxbox/flex/flex_usr.conf
/var/tuxbox/plugins/*.cfg
/var/tuxbox/plugins/*.conf
/etc/exports
/etc/hostname
/etc/hosts
/etc/network/interfaces
/etc/profile.local
/etc/rc.local
/etc/samba/smb.conf

## additional personal backups below this line
